// automatically generated by the FlatBuffers compiler, do not modify

package com.onee.rusty.model;

@SuppressWarnings("unused")
public final class Display {
  private Display() { }
  public static final int flex = 0;
  public static final int none = 1;

  public static final String[] names = { "flex", "none", };

  public static String name(int e) { return names[e]; }
}

