// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffer_generate;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BufferViewProperty extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static BufferViewProperty getRootAsBufferViewProperty(ByteBuffer _bb) { return getRootAsBufferViewProperty(_bb, new BufferViewProperty()); }
  public static BufferViewProperty getRootAsBufferViewProperty(ByteBuffer _bb, BufferViewProperty obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BufferViewProperty __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double width() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double height() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double marginLeft() { int o = __offset(8); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double marginRight() { int o = __offset(10); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double marginTop() { int o = __offset(12); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double marginBottom() { int o = __offset(14); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public int flex() { int o = __offset(16); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int display() { int o = __offset(18); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int flexDirection() { int o = __offset(20); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int backgroundColor() { int o = __offset(22); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int flexWrap() { int o = __offset(24); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String content() { int o = __offset(26); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(26, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 26, 1); }
  public String a() { int o = __offset(28); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer aAsByteBuffer() { return __vector_as_bytebuffer(28, 1); }
  public ByteBuffer aInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 28, 1); }
  public String b() { int o = __offset(30); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer bAsByteBuffer() { return __vector_as_bytebuffer(30, 1); }
  public ByteBuffer bInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 30, 1); }
  public String c() { int o = __offset(32); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer cAsByteBuffer() { return __vector_as_bytebuffer(32, 1); }
  public ByteBuffer cInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 32, 1); }
  public String d() { int o = __offset(34); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dAsByteBuffer() { return __vector_as_bytebuffer(34, 1); }
  public ByteBuffer dInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 34, 1); }
  public String e() { int o = __offset(36); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer eAsByteBuffer() { return __vector_as_bytebuffer(36, 1); }
  public ByteBuffer eInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 36, 1); }
  public String f() { int o = __offset(38); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer fAsByteBuffer() { return __vector_as_bytebuffer(38, 1); }
  public ByteBuffer fInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 38, 1); }
  public String g() { int o = __offset(40); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer gAsByteBuffer() { return __vector_as_bytebuffer(40, 1); }
  public ByteBuffer gInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 40, 1); }
  public String h() { int o = __offset(42); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hAsByteBuffer() { return __vector_as_bytebuffer(42, 1); }
  public ByteBuffer hInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 42, 1); }
  public String i() { int o = __offset(44); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer iAsByteBuffer() { return __vector_as_bytebuffer(44, 1); }
  public ByteBuffer iInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 44, 1); }
  public String j() { int o = __offset(46); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer jAsByteBuffer() { return __vector_as_bytebuffer(46, 1); }
  public ByteBuffer jInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 46, 1); }
  public String k() { int o = __offset(48); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer kAsByteBuffer() { return __vector_as_bytebuffer(48, 1); }
  public ByteBuffer kInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 48, 1); }
  public String l() { int o = __offset(50); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer lAsByteBuffer() { return __vector_as_bytebuffer(50, 1); }
  public ByteBuffer lInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 50, 1); }
  public String m() { int o = __offset(52); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mAsByteBuffer() { return __vector_as_bytebuffer(52, 1); }
  public ByteBuffer mInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 52, 1); }
  public String n() { int o = __offset(54); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nAsByteBuffer() { return __vector_as_bytebuffer(54, 1); }
  public ByteBuffer nInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 54, 1); }
  public String o() { int o = __offset(56); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer oAsByteBuffer() { return __vector_as_bytebuffer(56, 1); }
  public ByteBuffer oInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 56, 1); }

  public static int createBufferViewProperty(FlatBufferBuilder builder,
      double width,
      double height,
      double marginLeft,
      double marginRight,
      double marginTop,
      double marginBottom,
      int flex,
      int display,
      int flexDirection,
      int backgroundColor,
      int flexWrap,
      int contentOffset,
      int aOffset,
      int bOffset,
      int cOffset,
      int dOffset,
      int eOffset,
      int fOffset,
      int gOffset,
      int hOffset,
      int iOffset,
      int jOffset,
      int kOffset,
      int lOffset,
      int mOffset,
      int nOffset,
      int oOffset) {
    builder.startTable(27);
    BufferViewProperty.addMarginBottom(builder, marginBottom);
    BufferViewProperty.addMarginTop(builder, marginTop);
    BufferViewProperty.addMarginRight(builder, marginRight);
    BufferViewProperty.addMarginLeft(builder, marginLeft);
    BufferViewProperty.addHeight(builder, height);
    BufferViewProperty.addWidth(builder, width);
    BufferViewProperty.addO(builder, oOffset);
    BufferViewProperty.addN(builder, nOffset);
    BufferViewProperty.addM(builder, mOffset);
    BufferViewProperty.addL(builder, lOffset);
    BufferViewProperty.addK(builder, kOffset);
    BufferViewProperty.addJ(builder, jOffset);
    BufferViewProperty.addI(builder, iOffset);
    BufferViewProperty.addH(builder, hOffset);
    BufferViewProperty.addG(builder, gOffset);
    BufferViewProperty.addF(builder, fOffset);
    BufferViewProperty.addE(builder, eOffset);
    BufferViewProperty.addD(builder, dOffset);
    BufferViewProperty.addC(builder, cOffset);
    BufferViewProperty.addB(builder, bOffset);
    BufferViewProperty.addA(builder, aOffset);
    BufferViewProperty.addContent(builder, contentOffset);
    BufferViewProperty.addFlexWrap(builder, flexWrap);
    BufferViewProperty.addBackgroundColor(builder, backgroundColor);
    BufferViewProperty.addFlexDirection(builder, flexDirection);
    BufferViewProperty.addDisplay(builder, display);
    BufferViewProperty.addFlex(builder, flex);
    return BufferViewProperty.endBufferViewProperty(builder);
  }

  public static void startBufferViewProperty(FlatBufferBuilder builder) { builder.startTable(27); }
  public static void addWidth(FlatBufferBuilder builder, double width) { builder.addDouble(0, width, 0.0); }
  public static void addHeight(FlatBufferBuilder builder, double height) { builder.addDouble(1, height, 0.0); }
  public static void addMarginLeft(FlatBufferBuilder builder, double marginLeft) { builder.addDouble(2, marginLeft, 0.0); }
  public static void addMarginRight(FlatBufferBuilder builder, double marginRight) { builder.addDouble(3, marginRight, 0.0); }
  public static void addMarginTop(FlatBufferBuilder builder, double marginTop) { builder.addDouble(4, marginTop, 0.0); }
  public static void addMarginBottom(FlatBufferBuilder builder, double marginBottom) { builder.addDouble(5, marginBottom, 0.0); }
  public static void addFlex(FlatBufferBuilder builder, int flex) { builder.addInt(6, flex, 0); }
  public static void addDisplay(FlatBufferBuilder builder, int display) { builder.addInt(7, display, 0); }
  public static void addFlexDirection(FlatBufferBuilder builder, int flexDirection) { builder.addInt(8, flexDirection, 0); }
  public static void addBackgroundColor(FlatBufferBuilder builder, int backgroundColor) { builder.addInt(9, backgroundColor, 0); }
  public static void addFlexWrap(FlatBufferBuilder builder, int flexWrap) { builder.addInt(10, flexWrap, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(11, contentOffset, 0); }
  public static void addA(FlatBufferBuilder builder, int aOffset) { builder.addOffset(12, aOffset, 0); }
  public static void addB(FlatBufferBuilder builder, int bOffset) { builder.addOffset(13, bOffset, 0); }
  public static void addC(FlatBufferBuilder builder, int cOffset) { builder.addOffset(14, cOffset, 0); }
  public static void addD(FlatBufferBuilder builder, int dOffset) { builder.addOffset(15, dOffset, 0); }
  public static void addE(FlatBufferBuilder builder, int eOffset) { builder.addOffset(16, eOffset, 0); }
  public static void addF(FlatBufferBuilder builder, int fOffset) { builder.addOffset(17, fOffset, 0); }
  public static void addG(FlatBufferBuilder builder, int gOffset) { builder.addOffset(18, gOffset, 0); }
  public static void addH(FlatBufferBuilder builder, int hOffset) { builder.addOffset(19, hOffset, 0); }
  public static void addI(FlatBufferBuilder builder, int iOffset) { builder.addOffset(20, iOffset, 0); }
  public static void addJ(FlatBufferBuilder builder, int jOffset) { builder.addOffset(21, jOffset, 0); }
  public static void addK(FlatBufferBuilder builder, int kOffset) { builder.addOffset(22, kOffset, 0); }
  public static void addL(FlatBufferBuilder builder, int lOffset) { builder.addOffset(23, lOffset, 0); }
  public static void addM(FlatBufferBuilder builder, int mOffset) { builder.addOffset(24, mOffset, 0); }
  public static void addN(FlatBufferBuilder builder, int nOffset) { builder.addOffset(25, nOffset, 0); }
  public static void addO(FlatBufferBuilder builder, int oOffset) { builder.addOffset(26, oOffset, 0); }
  public static int endBufferViewProperty(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishBufferViewPropertyBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedBufferViewPropertyBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BufferViewProperty get(int j) { return get(new BufferViewProperty(), j); }
    public BufferViewProperty get(BufferViewProperty obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

