// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffer_generate;

@SuppressWarnings("unused")
public final class BufferFlexDirection {
  private BufferFlexDirection() { }
  public static final int column = 0;
  public static final int column_reverse = 1;
  public static final int row = 2;
  public static final int row_reverse = 3;

  public static final String[] names = { "column", "column_reverse", "row", "row_reverse", };

  public static String name(int e) { return names[e]; }
}

