// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffer_generate;

@SuppressWarnings("unused")
public final class BufferDisplay {
  private BufferDisplay() { }
  public static final int flex = 0;
  public static final int none = 1;

  public static final String[] names = { "flex", "none", };

  public static String name(int e) { return names[e]; }
}

