// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffer_generate;

@SuppressWarnings("unused")
public final class BufferFlexWrap {
  private BufferFlexWrap() { }
  public static final int nowrap = 0;
  public static final int wrap = 1;

  public static final String[] names = { "nowrap", "wrap", };

  public static String name(int e) { return names[e]; }
}

