// Automatically generated by the Flatbuffers compiler. Do not modify.
pub mod com {
  use super::*;
  pub mod onee {
    use super::*;
    pub mod rusty {
      use super::*;
      pub mod model {
        use super::*;
        mod display_generated;
        pub use self::display_generated::*;
        mod flex_direction_generated;
        pub use self::flex_direction_generated::*;
        mod flex_wrap_generated;
        pub use self::flex_wrap_generated::*;
        mod view_property_generated;
        pub use self::view_property_generated::*;
      } // model
    } // rusty
  } // onee
} // com
