# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for ios
  pod 'rustlib', path: '../rust'

end
