// Automatically generated by flapigen
package com.onee.rusty.glue;
import androidx.annotation.NonNull;

public final class CollectionMap {

    private CollectionMap() {}

    public final @NonNull java.lang.String [] importKeys() {
        java.lang.String [] ret = do_importKeys(mNativeObj);

        return ret;
    }
    private static native @NonNull java.lang.String [] do_importKeys(long self);

    public final @NonNull CollectionValue [] importValues() {
        CollectionValue [] ret = do_importValues(mNativeObj);

        return ret;
    }
    private static native @NonNull CollectionValue [] do_importValues(long self);

    public final int [] rawImportTypes() {
        int [] ret = do_rawImportTypes(mNativeObj);

        return ret;
    }
    private static native int [] do_rawImportTypes(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ CollectionMap(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;

    public ValueType[] importTypes() {
        int[] rawTypes = rawImportTypes();
        ValueType[] types = new ValueType[rawTypes.length];
        for (int i = 0;i < types.length;i++) {
            types[i] = ValueType.fromInt(rawTypes[i]);
        }
        return types;
    }
    }