// Automatically generated by flapigen
package com.onee.rusty.glue;
import androidx.annotation.NonNull;

public final class CommandList {

    private CommandList() {}

    public final long length() {
        long ret = do_length(mNativeObj);

        return ret;
    }
    private static native long do_length(long self);

    public final @NonNull Command get(long a0) {
        long ret = do_get(mNativeObj, a0);
        Command convRet = new Command(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_get(long self, long a0);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ CommandList(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}