// Automatically generated by flapigen
package com.onee.rusty.glue;
import androidx.annotation.NonNull;

public final class Command {

    private Command() {}

    public final CommandType commandType() {
        int ret = do_commandType(mNativeObj);
        CommandType convRet = CommandType.fromInt(ret);

        return convRet;
    }
    private static native int do_commandType(long self);

    public final long tag() {
        long ret = do_tag(mNativeObj);

        return ret;
    }
    private static native long do_tag(long self);

    public final @NonNull String className() {
        String ret = do_className(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_className(long self);

    public final long rootViewTag() {
        long ret = do_rootViewTag(mNativeObj);

        return ret;
    }
    private static native long do_rootViewTag(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Command(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}