// Automatically generated by flapigen
package com.onee.rusty.glue;


public enum CommandType {
    CreateView(0),
    SetChild(1);

    private final int value;
    CommandType(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static CommandType fromInt(int x) {
        switch (x) {
            case 0: return CreateView;
            case 1: return SetChild;
            default: throw new Error("Invalid value for enum CommandType: " + x);
        }
    }
}
