// Automatically generated by flapigen
package com.onee.rusty.glue;
import androidx.annotation.NonNull;

public final class Engine {

    public Engine() {
        mNativeObj = init();
    }
    private static native long init();

    public final void launch() {
        do_launch(mNativeObj);
    }
    private static native void do_launch(long self);

    public final @NonNull CommandList run_app(int a0) {
        long ret = do_run_app(mNativeObj, a0);
        CommandList convRet = new CommandList(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_run_app(long self, int a0);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Engine(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}