// Automatically generated by flapigen
package com.onee.rusty.glue;
import androidx.annotation.NonNull;

public final class PropertyList {

    private PropertyList() {}

    public final long length() {
        long ret = do_length(mNativeObj);

        return ret;
    }
    private static native long do_length(long self);

    public final @NonNull String get(long a0) {
        String ret = do_get(mNativeObj, a0);

        return ret;
    }
    private static native @NonNull String do_get(long self, long a0);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ PropertyList(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;

    public com.facebook.react.bridge.JavaOnlyMap toMap() {
        com.facebook.react.bridge.JavaOnlyMap map = new com.facebook.react.bridge.JavaOnlyMap();
        for (int i = 0;i < this.length();i += 2) {
            map.putDouble(this.get(i), Double.parseDouble(this.get(i + 1)));
        }
        return map;
    }
    }