// Automatically generated by flapigen
package com.onee.rusty.glue;
import androidx.annotation.NonNull;

public interface UIManager {


    void createView(int tag, @NonNull String class_name, int root_view_tag, @NonNull PropertyMap properties);


    void setChildren(int tag, @NonNull int [] children);


    void onBatchComplete();

}
