// Automatically generated by flapigen
package com.onee.rusty.glue;


public enum ValueType {
    Null(0),
    Boolean(1),
    Number(2),
    String(3),
    Map(4),
    Array(5);

    private final int value;
    ValueType(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static ValueType fromInt(int x) {
        switch (x) {
            case 0: return Null;
            case 1: return Boolean;
            case 2: return Number;
            case 3: return String;
            case 4: return Map;
            case 5: return Array;
            default: throw new Error("Invalid value for enum ValueType: " + x);
        }
    }
}
