// Automatically generated by flapigen
package com.onee.rusty;
import androidx.annotation.NonNull;

public final class Command {

    public Command() {
        mNativeObj = init();
    }
    private static native long init();

    public final CommandType get_commandType() {
        int ret = do_get_commandType(mNativeObj);
        CommandType convRet = CommandType.fromInt(ret);

        return convRet;
    }
    private static native int do_get_commandType(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Command(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}