// Automatically generated by flapigen
package com.onee.rusty;
import androidx.annotation.NonNull;

public final class CommandList {

    public CommandList() {
        mNativeObj = init();
    }
    private static native long init();

    public final long len() {
        long ret = do_len(mNativeObj);

        return ret;
    }
    private static native long do_len(long self);

    public final @NonNull Command at(long i) {
        long ret = do_at(mNativeObj, i);
        Command convRet = new Command(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_at(long self, long i);

    public final void push_back(@NonNull Command s) {
        long a0 = s.mNativeObj;
        s.mNativeObj = 0;

        do_push_back(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(s);
    }
    private static native void do_push_back(long self, long s);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ CommandList(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}