// Automatically generated by flapigen
package com.onee.rusty;


public final class Foo {

    public Foo(int a0) {
        mNativeObj = init(a0);
    }
    private static native long init(int a0);

    public final void set_field(int a0) {
        do_set_field(mNativeObj, a0);
    }
    private static native void do_set_field(long self, int a0);

    public final int f(int a0, int a1) {
        int ret = do_f(mNativeObj, a0, a1);

        return ret;
    }
    private static native int do_f(long self, int a0, int a1);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Foo(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}